nodeLinker: node-modules

npmScopes:
  abr:
    npmAuthToken: "${NIPOTO_NPM_TOKEN}"
    npmRegistryServer: "https://git.services.iranpage.net/api/v4/groups/37/-/packages/npm/"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
